appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: t+VnhC75BABxGLXZXpWfmu/DUy7uLDVN/MYVZ34BCUn5BN7p+eU+wCXZbxg4WD8Aj0g9mmFq7eG369krH8tX2pVFdT+fLsS1tFUjII3kbAg4lmog2iu1bUIgk1yqxhM/lbk6P5vJekOmcGc1QKLrujHAvGuel5iOWok9EB4s1YcHuTIlXEEKciUt7fYSZUx5G2iLIItncmsJmwLD3ZC5yYvBfICEe+S6gMXxs5l7y8AF7PYp8dWZF8XqLy3vNOvUZlIkrJwu9g5dCQeorEBVc6w5DPEQ/Y6zZkQ9mjx+FK/z9A/b2anouy7APc8/8sEpiaMaznW0hPCn41yyyrQsIvChlfImaetz1OCoMbZEW7PPwVO0RsVz8b1rYBB2rkaT/EGeiA+O546L8qLoByosDubIlmhYY1befIlnt+S7xQGw5anvUeFaRcpUY0c3vDeJHztbirTCb2rswOfdEAN0q/0JTSuZIzAIME9Kw3fHpCPdxzUebT7Df5Nal9lpkWCmabZJoqKJWtT7Qbqn9/bgRwECItrlm9Zl6mloh7ZxcxaiOpiKiV7zjVXec2YgLdOsa1HWNZT0HaxHr/amS9W8dQktf7HkmMdWdZMajOGQx3aABk/feYGtFup39IRIXBTtgxgXJLo7MO4bsjjr1fI1JC/VUd45rE9iPq9lsDMvrg0=}
