travis:
  secure:
    BINSTAR_TOKEN: ysh+LfRjJUi5mdg08xZ6Ms+dMzTTeRTDCT5/c1FSc1Rkwl52p7fLQ0UDgVxlVUoC7rvowZbVZ7QRLbbHZSL/E9pdxVZUHXMHS3izYylZ17wTg8aOiRQgedcAfB35+koOJM0BUKMpfTWuXu9ECgZOGdMheSPWeWfJLopXGNDgfZnsd5ivcXOCFvtrn0gPmLRJPDNluUiul7PCFLZVssF4y7i4y7tPIn5NrbBiFCvqfTQ5420M2uT9/qzs3Rja6r/SqmgqgHitmlz6dyDyWkMx+ixshCtIesfeB0jPq57mbGNNnG5vOfPNpBgJul18EIz8IBUUqUKm3hz64JncD7tf87d5SX1cGGZtkJ0BXnlrC6+Drd82rXkrcd14tFzRv0NtoZHCzNIj2h1+fGpYGcvBJQ0rfuq5deEVwi1X+W8CxEyANek/FLlgeYB125h9hpkf+unoGQEcHOngHrAOoaBpqLBsSs2iDXFMwiG0JX0w26oAo3yIVzVj2Ax3nqPb6shQ8wZ3sCwVXq4gj0VymrGvz+eKzEnhXGPcVAzCeuROKDwI26rz20r1uHUeRWgvb3FN859IHth5k3H478wTe73E1VjYIPof8vo8LGoJ9S2iJrlVKl9iKmzcmlYFnJHOI1KOcZ3vJrkAN217mOWJtgh6tK40gHFOOZC6EQF5QPLPrGA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
